language: python
python:
- '2.7'
- '3.4'
install:
- pip install tox
- pip install pex
- pip install -r requirements.txt
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')
- pex . --no-wheel -o dist/missingtvshows$(echo py$TRAVIS_PYTHON_VERSION | tr -d .).pex -e mtvs.main:main  -r pex_private_requirements.txt -r pex_public_requirements.txt
- tox -e docs
notifications:
  slack:
    secure: PGoIf/m17cPQAVW/8oIork4qg2uYyLPAGaZ+ral9E3E7E2NTshtnD28YoMWYflBu/W2BFot11h/tgYrcyxRNv8U/5RDezS8lMtwKroc4OxbVI86W20pwuepPsKgovbWXYkmGvsRuzqxiewA3Tqd1g+xAArLOjx3eQ+KQTxTrJHQl1UGZhR8SI3Anhdp7dhlbIUk69QCumtRGGbWJ12oUdU5jm/u0mLz7fnrnu1ytqrRXial6wQ+89WtN5egv9py5YXxXwci3ANWcqgJIUubdOIEgQIlYuwhtum3HQgumbTUE6pX1G8UHuELMaQfDVccCItfW8geaKS3P8syg9sSX3787x6RhDPGTZjaVhMTYIYSOT+aQztIVv6d+RJ53Wdnb/kdnN7T5dt9KK4c9owF5IvA9xhFZEQafJ11hj8C/PBAxadqUKc5rLT/+VKy0FoSwX/zAAIV2j4BrHf8EeyaXh7WEYALbMZofVYWkMZeJANMWP+quvGnPixHCVzlD5S86MCd+zJxXtvXrWZ1n6ts26s7FW/SjnhY8roTKFwqPFqINpIdQd07j4m+5FybV12zt4d+O48/wypLZGfBfdU040PMZbBgVsz46Km1GUUrnJrP8NHTffmktZ9Pk4PT3YeU9LSZ6JvMW0yjnDkg3pYe12W8ggbF79TCVOhJAphOmsWA=
  email:
    recipients:
    - andreas.ruppen@gmail.com
    on_success: change
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: "P0xV5u4whHU3o9eiC67npdaXLVwpKZykicmNgGq4GreP2GFjJyo4JZFYeaaKYek35ju7Db3hI0rAr7ElKKSdtlgztoyo2IsGUbVwWSD+yLZBmypXhwaWVF/zD/EO3cx+Io7pj/62U9tq7a5fOsTH+SPkP7lL73+hN1vKY016Sk0MHFoInC2l2GOjnV+cW8bM3sb1BC9zB7Yh/ExZCgigwhtqNYb9zfCHo/79oN939fGzdOp14z4rSCxS34cMzWirW46ZWXKa4Jief0izkLO9KVm3FA+ySmPex0gZsOxMDVCemuqdRjaBPB7uhe/mnDqNodgAsN8nI3Cfx6oYc6j1tiBx+i5F2MjbZUv6JV41gYdW+PtCM3adLaaxPvlcPuqZ0N1cVytYvp73I59v+0e2Ae3mv1dPjXnrdsQ/eIdBZv0XV9MxaGcWh8wJeu+FMhtvXmyENctZekY3+M9pqBSXGvnuM9o6TnyjPmREmzCikrXN7B5qLmu8FOXWAIUE53hD46X4jfvcMFUADc1FXqaAIp+R55euHHmp8dbCKEWbdTwEjdKRKsmCfGicGZE+1bc77Fk438f6CB2afBm9+Uuh8j3rpp7Oj5yOkzKyJ7wwJAqiCaLYBzn3upWWYWgbNieQjFjqf+8jLIQFkItvyXKpvxDF+SHiqzN6DZP7gXDIUa0="
  file:
  - dist/missingtvshows$(echo py$TRAVIS_PYTHON_VERSION | tr -d .).pex
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
